Imports

In [3]:
import pandas as pd

Cargar dataset

In [8]:
df = pd.read_excel("../data/Online Retail.xlsx", sheet_name=0)

# Exploring StockCode

Vamos a realizar en esta notebook la exploración de los "StockCode" porque sino nos va agregar ruido innecesario a nuestro EDA.

Al final vamos a incluir un resumen sobre qué vamos a hacer con cada variedad, para definir si las incluimos en el análisis o si es mejor descartarlas.

In [16]:
df["StockCode"] = df["StockCode"].astype(str)
df["InvoiceNo"] = df["InvoiceNo"].astype(str)

In [18]:
df[~df["StockCode"].str.match(r"^\d{5}[a-zA-Z]*$")]["StockCode"].unique()

array(['POST', 'D', 'C2', 'DOT', 'M', 'BANK CHARGES', 'S', 'AMAZONFEE',
       'DCGS0076', 'DCGS0003', 'gift_0001_40', 'DCGS0070', 'm',
       'gift_0001_50', 'gift_0001_30', 'gift_0001_20', 'DCGS0055',
       'DCGS0072', 'DCGS0074', 'DCGS0069', 'DCGS0057', 'DCGSSBOY',
       'DCGSSGIRL', 'gift_0001_10', 'PADS', 'DCGS0004', 'DCGS0073',
       'DCGS0071', 'DCGS0068', 'DCGS0067', 'DCGS0066P', 'B', 'CRUK'],
      dtype=object)

In [13]:
df[df["StockCode"].str.startswith("POST")]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.0,12583.0,France
386,536403,POST,POSTAGE,1,2010-12-01 11:27:00,15.0,12791.0,Netherlands
1123,536527,POST,POSTAGE,1,2010-12-01 13:04:00,18.0,12662.0,Germany
5073,536840,POST,POSTAGE,1,2010-12-02 18:27:00,18.0,12738.0,Germany
5258,536852,POST,POSTAGE,1,2010-12-03 09:51:00,18.0,12686.0,France
...,...,...,...,...,...,...,...,...
541198,581493,POST,POSTAGE,1,2011-12-09 10:10:00,15.0,12423.0,Belgium
541216,581494,POST,POSTAGE,2,2011-12-09 10:13:00,18.0,12518.0,Germany
541730,581570,POST,POSTAGE,1,2011-12-09 11:59:00,18.0,12662.0,Germany
541767,581574,POST,POSTAGE,2,2011-12-09 12:09:00,18.0,12526.0,Germany
541768,581578,POST,POSTAGE,3,2011-12-09 12:16:00,18.0,12713.0,Germany

A primera vista, parece el costo asociado al envío. Queremos ver si se trata de una factura común y corriente, es decir, que tiene otras compras en la misma.

Por eso veamos un caso en particular, por ejemplo el primero.

In [17]:
df[df["InvoiceNo"] == "536370"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France
31,536370,10002,INFLATABLE POLITICAL GLOBE,48,2010-12-01 08:45:00,0.85,12583.0,France
32,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,2010-12-01 08:45:00,1.25,12583.0,France
33,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,2010-12-01 08:45:00,2.95,12583.0,France
34,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,2010-12-01 08:45:00,2.95,12583.0,France
35,536370,22629,SPACEBOY LUNCH BOX,24,2010-12-01 08:45:00,1.95,12583.0,France
36,536370,22659,LUNCH BOX I LOVE LONDON,24,2010-12-01 08:45:00,1.95,12583.0,France
37,536370,22631,CIRCUS PARADE LUNCH BOX,24,2010-12-01 08:45:00,1.95,12583.0,France
38,536370,22661,CHARLOTTE BAG DOLLY GIRL DESIGN,20,2010-12-01 08:45:00,0.85,12583.0,France
39,536370,21731,RED TOADSTOOL LED NIGHT LIGHT,24,2010-12-01 08:45:00,1.65,12583.0,France
40,536370,22900,SET 2 TEA TOWELS I LOVE LONDON,24,2010-12-01 08:45:00,2.95,12583.0,France
41,536370,21913,VINTAGE SEASIDE JIGSAW PUZZLES,12,2010-12-01 08:45:00,3.75,12583.0,France
42,536370,22540,MINI JIGSAW CIRCUS PARADE,24,2010-12-01 08:45:00,0.42,12583.0,France
43,536370,22544,MINI JIGSAW SPACEBOY,24,2010-12-01 08:45:00,0.42,12583.0,France
44,536370,22492,MINI PAINT SET VINTAGE,36,2010-12-01 08:45:00,0.65,12583.0,France
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.00,12583.0,France

Es el costo asociado al envío.

In [19]:
df[df["StockCode"] == "D"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
9038,C537164,D,Discount,-1,2010-12-05 13:21:00,29.29,14527.0,United Kingdom
14498,C537597,D,Discount,-1,2010-12-07 12:34:00,281.00,15498.0,United Kingdom
19392,C537857,D,Discount,-1,2010-12-08 16:00:00,267.12,17340.0,United Kingdom
31134,C538897,D,Discount,-1,2010-12-15 09:14:00,5.76,16422.0,United Kingdom
...,...,...,...,...,...,...,...,...
479868,C577227,D,Discount,-1,2011-11-18 12:06:00,19.82,14527.0,United Kingdom
479869,C577227,D,Discount,-1,2011-11-18 12:06:00,16.76,14527.0,United Kingdom
493613,C578239,D,Discount,-1,2011-11-23 12:29:00,26.33,14912.0,Italy
516221,C579884,D,Discount,-1,2011-11-30 17:34:00,20.53,14527.0,United Kingdom
516455,C579908,D,Discount,-1,2011-12-01 08:49:00,28.68,14527.0,United Kingdom

Parecen ser lineas de ventas destinadas a representar un descuento, por eso la cantidad es negativa. Vemos si realmente esto se da siempre.

In [20]:
df[df["StockCode"] == "D"]["Quantity"].unique()

array([  -1, -720, -240,  -18,  -48,  -96])

Tal parece que sí. Vamos a excluir de nuestro análisis los descuentos.

In [22]:
df[df["StockCode"] == "C2"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1423,536540,C2,CARRIAGE,1,2010-12-01 14:05:00,50.0,14911.0,EIRE
12119,537368,C2,CARRIAGE,1,2010-12-06 12:40:00,50.0,14911.0,EIRE
12452,537378,C2,CARRIAGE,1,2010-12-06 13:06:00,50.0,14911.0,EIRE
19975,537963,C2,CARRIAGE,1,2010-12-09 11:30:00,50.0,13369.0,United Kingdom
20016,538002,C2,CARRIAGE,1,2010-12-09 11:48:00,50.0,14932.0,Channel Islands
34369,539337,C2,CARRIAGE,1,2010-12-17 10:46:00,50.0,NaN,EIRE
34725,539421,C2,CARRIAGE,1,2010-12-17 14:21:00,50.0,14016.0,EIRE
37644,539473,C2,CARRIAGE,1,2010-12-19 14:24:00,50.0,14911.0,EIRE
39777,539688,C2,CARRIAGE,1,2010-12-21 11:00:00,150.0,12678.0,France
42332,539984,C2,CARRIAGE,1,2010-12-23 14:58:00,50.0,14911.0,EIRE

In [26]:
df[df["StockCode"] == "C2"]["Description"].unique()

array(['CARRIAGE', nan], dtype=object)

Este tipo de registros también parecen asociados a envíos. Vamos a descartarlos.

In [28]:
df[df["StockCode"] == "DOT"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1814,536544,DOT,DOTCOM POSTAGE,1,2010-12-01 14:32:00,569.77,NaN,United Kingdom
3041,536592,DOT,DOTCOM POSTAGE,1,2010-12-01 17:06:00,607.49,NaN,United Kingdom
5450,536862,DOT,DOTCOM POSTAGE,1,2010-12-03 11:13:00,254.43,NaN,United Kingdom
5545,536864,DOT,DOTCOM POSTAGE,1,2010-12-03 11:27:00,121.06,NaN,United Kingdom
5685,536865,DOT,DOTCOM POSTAGE,1,2010-12-03 11:28:00,498.47,NaN,United Kingdom
6165,536876,DOT,DOTCOM POSTAGE,1,2010-12-03 11:36:00,887.52,NaN,United Kingdom
10812,537237,DOT,DOTCOM POSTAGE,1,2010-12-06 09:58:00,863.74,NaN,United Kingdom
11381,537240,DOT,DOTCOM POSTAGE,1,2010-12-06 10:08:00,940.87,NaN,United Kingdom
13924,537434,DOT,DOTCOM POSTAGE,1,2010-12-06 16:57:00,950.99,NaN,United Kingdom
15650,537638,DOT,DOTCOM POSTAGE,1,2010-12-07 15:28:00,836.14,NaN,United Kingdom

Estos también parecen estar relacionados con costos de envío. Y vemos que de la muestra de 10 que tomamos, ninguno tiene un "CustomerID" asociado. Al igual que con los demás, vamos a descartar estos.

In [30]:
df[df["StockCode"] == "M"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2239,536569,M,Manual,1,2010-12-01 15:35:00,1.25,16274.0,United Kingdom
2250,536569,M,Manual,1,2010-12-01 15:35:00,18.95,16274.0,United Kingdom
5684,536865,M,Manual,1,2010-12-03 11:28:00,2.55,NaN,United Kingdom
6798,536981,M,Manual,2,2010-12-03 14:26:00,0.85,14723.0,United Kingdom
7976,537077,M,Manual,12,2010-12-05 11:59:00,0.42,17062.0,United Kingdom
8530,537137,M,Manual,36,2010-12-05 12:43:00,0.85,16327.0,United Kingdom
8587,537140,M,Manual,1,2010-12-05 12:53:00,0.42,12748.0,United Kingdom
8588,537140,M,Manual,1,2010-12-05 12:53:00,0.85,12748.0,United Kingdom
9326,537199,M,Manual,1,2010-12-05 14:06:00,0.65,15894.0,United Kingdom
9575,537208,M,Manual,4,2010-12-05 15:12:00,0.85,15889.0,United Kingdom

In [31]:
df[df["StockCode"] == "M"].describe()

          Quantity                    InvoiceDate     UnitPrice    CustomerID
count   571.000000                            571    571.000000    465.000000
mean      5.541156  2011-06-26 23:03:50.332749568    375.566392  15275.187097
min   -1350.000000            2010-12-01 15:35:00      0.000000  12352.000000
25%      -1.000000            2011-03-31 11:42:00      1.000000  13263.000000
50%       1.000000            2011-07-10 12:16:00      7.950000  15502.000000
75%       1.000000            2011-10-10 13:37:00    278.065000  16928.000000
max    1600.000000            2011-12-09 10:28:00  38970.000000  18283.000000
std     120.374065                            NaN   1773.398610   1873.733814

In [36]:
df[df["InvoiceNo"] == "536981"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6796,536981,22222,CAKE PLATE LOVEBIRD WHITE,1,2010-12-03 14:26:00,4.95,14723.0,United Kingdom
6797,536981,22154,ANGEL DECORATION 3 BUTTONS,3,2010-12-03 14:26:00,0.42,14723.0,United Kingdom
6798,536981,M,Manual,2,2010-12-03 14:26:00,0.85,14723.0,United Kingdom
6799,536981,21592,RETROSPOT CIGAR BOX MATCHES,2,2010-12-03 14:26:00,1.25,14723.0,United Kingdom
6800,536981,22158,3 HEARTS HANGING DECORATION RUSTIC,1,2010-12-03 14:26:00,2.95,14723.0,United Kingdom
6801,536981,48138,DOORMAT UNION FLAG,1,2010-12-03 14:26:00,7.95,14723.0,United Kingdom
6802,536981,22130,PARTY CONE CHRISTMAS DECORATION,6,2010-12-03 14:26:00,0.85,14723.0,United Kingdom
6803,536981,22095,LADS ONLY TISSUE BOX,1,2010-12-03 14:26:00,1.25,14723.0,United Kingdom
6804,536981,21982,PACK OF 12 SUKI TISSUES,1,2010-12-03 14:26:00,0.29,14723.0,United Kingdom
6805,536981,21169,YOU'RE CONFUSING ME METAL SIGN,1,2010-12-03 14:26:00,1.69,14723.0,United Kingdom

Este caso es más complicado. Parece que se tratan de cargas en facturas que se hacen manualmente.

Esto puede ser debido a que no tienen un código asociado a ese producto en ese momento, o cuando se trata de ajustes de stock.

Son pocos, alrededor de 500 registros, en primera instancia creemos que deberíamos incluirlos porque afectan al total de la factura. Pero ante la duda, y siendo que son pocos, preferimos descartarlos.

In [37]:
df[df["StockCode"] == "BANK CHARGES"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
4406,536779,BANK CHARGES,Bank Charges,1,2010-12-02 15:08:00,15.00,15823.0,United Kingdom
14435,C537572,BANK CHARGES,Bank Charges,-1,2010-12-07 12:00:00,95.38,NaN,United Kingdom
28992,C538680,BANK CHARGES,Bank Charges,-1,2010-12-13 17:10:00,966.92,NaN,United Kingdom
62508,541505,BANK CHARGES,Bank Charges,1,2011-01-18 15:58:00,15.00,15939.0,United Kingdom
64573,C541653,BANK CHARGES,Bank Charges,-1,2011-01-20 11:50:00,1050.15,NaN,United Kingdom
90558,C544049,BANK CHARGES,Bank Charges,-1,2011-02-15 12:39:00,566.37,NaN,United Kingdom
96675,C544575,BANK CHARGES,Bank Charges,-1,2011-02-21 13:58:00,134.76,NaN,United Kingdom
96676,C544576,BANK CHARGES,Bank Charges,-1,2011-02-21 14:01:00,149.16,NaN,United Kingdom
96715,C544584,BANK CHARGES,Bank Charges,-1,2011-02-21 14:52:00,109.84,NaN,United Kingdom
112233,C545887,BANK CHARGES,Bank Charges,-1,2011-03-07 15:54:00,326.68,NaN,United Kingdom

In [38]:
df[df["StockCode"] == "BANK CHARGES"].describe()

        Quantity                    InvoiceDate    UnitPrice    CustomerID
count  37.000000                             37    37.000000     12.000000
mean   -0.351351  2011-06-23 10:11:40.540540416   202.855162  14949.083333
min    -1.000000            2010-12-02 15:08:00     0.001000  13263.000000
25%    -1.000000            2011-03-07 15:54:00    15.000000  13589.500000
50%    -1.000000            2011-06-28 14:50:00    82.730000  14704.000000
75%     1.000000            2011-10-10 15:21:00   366.270000  16022.000000
max     1.000000            2011-12-07 12:45:00  1050.150000  16904.000000
std     0.949158                            NaN   271.788843   1347.114118

Parece ser una linea para indicar costos adicionales relacionados al banco. Son 37 casos únicamente. Y tan solo 12 de ellos tienen un "CustomerID" asociado. Vamos a descartarlos.

In [39]:
df[df["StockCode"] == "S"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
14436,C537581,S,SAMPLES,-1,2010-12-07 12:03:00,12.95,NaN,United Kingdom
14437,C537581,S,SAMPLES,-1,2010-12-07 12:03:00,52.00,NaN,United Kingdom
96680,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,5.74,NaN,United Kingdom
96681,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,11.08,NaN,United Kingdom
96682,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,5.79,NaN,United Kingdom
96683,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,6.70,NaN,United Kingdom
96684,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,8.74,NaN,United Kingdom
96685,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,9.74,NaN,United Kingdom
96686,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,9.99,NaN,United Kingdom
96687,C544580,S,SAMPLES,-1,2011-02-21 14:25:00,20.98,NaN,United Kingdom

Parecen ser muestras gratis de productos dados a los clientes.

Podrían ser importantes sin en efecto lo que hacen es anular el precio de productos en las facturas de clientes. Pero son pocos casos. Veamos un poco más:

In [40]:
df[df["StockCode"] == "S"].describe()

        Quantity                    InvoiceDate   UnitPrice  CustomerID
count  63.000000                             63   63.000000         0.0
mean   -0.936508  2011-05-05 18:09:41.904761856   50.404603         NaN
min    -1.000000            2010-12-07 12:03:00    2.800000         NaN
25%    -1.000000            2011-02-21 14:25:00    8.215000         NaN
50%    -1.000000            2011-03-18 11:20:00   19.500000         NaN
75%    -1.000000            2011-06-28 14:47:00   60.425000         NaN
max     1.000000            2011-11-18 14:16:00  570.000000         NaN
std     0.353463                            NaN   85.659017         NaN

Ninguno de estos registros de muestra gratis tiene un "CustomerID" asociado. Vamos a descartarlos.

In [41]:
df[df["StockCode"] == "AMAZONFEE"].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
14514,C537600,AMAZONFEE,AMAZON FEE,-1,2010-12-07 12:41:00,1.00,NaN,United Kingdom
15016,C537630,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:04:00,13541.33,NaN,United Kingdom
15017,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom
16232,C537644,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:34:00,13474.79,NaN,United Kingdom
16313,C537647,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:41:00,5519.25,NaN,United Kingdom
16356,C537651,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:49:00,13541.33,NaN,United Kingdom
16357,C537652,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:51:00,6706.71,NaN,United Kingdom
43702,C540117,AMAZONFEE,AMAZON FEE,-1,2011-01-05 09:55:00,16888.02,NaN,United Kingdom
43703,C540118,AMAZONFEE,AMAZON FEE,-1,2011-01-05 09:57:00,16453.71,NaN,United Kingdom
96844,C544587,AMAZONFEE,AMAZON FEE,-1,2011-02-21 15:07:00,5575.28,NaN,United Kingdom

In [42]:
df[df["StockCode"] == "AMAZONFEE"].describe()

        Quantity                    InvoiceDate     UnitPrice  CustomerID
count  34.000000                             34     34.000000         0.0
mean   -0.882353  2011-05-24 07:57:31.764705792   7324.784706         NaN
min    -1.000000            2010-12-07 12:41:00      1.000000         NaN
25%    -1.000000            2011-01-17 05:14:30   5233.465000         NaN
50%    -1.000000            2011-06-05 01:14:30   5909.875000         NaN
75%    -1.000000            2011-09-10 02:05:45   8071.657500         NaN
max     1.000000            2011-12-05 11:36:00  17836.460000         NaN
std     0.477665                            NaN   4619.549649         NaN

Parecen ser tarifas cobradas por Amazon por ventas por medio de su plataforma. Sea lo que sea, son tan solo 34 registros y ninguno tiene un "CustomerID" asignado. Vamos a descartar esto.

In [44]:
df[df["StockCode"].str.startswith("DCGS")].describe()

        Quantity                    InvoiceDate  UnitPrice  CustomerID
count  45.000000                             45  45.000000         0.0
mean    1.000000  2011-05-02 21:13:42.666666752   3.604889         NaN
min   -11.000000            2010-12-09 14:09:00   0.000000         NaN
25%    -1.000000            2011-02-07 14:04:00   0.000000         NaN
50%     1.000000            2011-04-18 13:13:00   3.290000         NaN
75%     2.000000            2011-07-26 11:51:00   3.290000         NaN
max    20.000000            2011-12-01 16:22:00  16.630000         NaN
std     5.456439                            NaN   4.495469         NaN

De todos estos "StockCode" que comienzan con DCGS. Ninguno tiene un "CustomerID" asociado. No nos sirven. Vamos a descartarlos.

In [45]:
df[df["StockCode"].str.startswith("gift")].describe()

        Quantity                    InvoiceDate  UnitPrice  CustomerID
count  34.000000                             34  34.000000         0.0
mean    3.029412  2011-05-27 01:18:38.823529216  19.435588         NaN
min     1.000000            2010-12-20 10:14:00   0.000000         NaN
25%     1.000000            2011-03-14 16:54:00   8.330000         NaN
50%     1.000000            2011-06-08 12:26:30  16.670000         NaN
75%     1.000000            2011-08-09 04:47:45  25.000000         NaN
max    30.000000            2011-12-08 09:20:00  42.550000         NaN
std     7.017231                            NaN  12.341874         NaN

De vuelta lo mismo. Los que empiezan con "gift" parecerían indicar regalos. Pero de todas formas ninguno tiene un "CustomerID" así que los descartamos.

In [46]:
df[df["StockCode"] == "m"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
40383,539736,m,Manual,1,2010-12-21 15:18:00,2.55,NaN,United Kingdom

Era de estas cargas manuales, solo que con la m minúscula. También lo descartamos. Es uno solo y no tiene un "CustomerID" asociado.

In [47]:
df[df["StockCode"] == "PADS"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
157195,550193,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-04-15 09:27:00,0.001,13952.0,United Kingdom
279045,561226,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-07-26 10:13:00,0.001,15618.0,United Kingdom
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.000,16133.0,United Kingdom
359871,568200,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 14:58:00,0.001,16198.0,United Kingdom

Esto, traducido, parece tratarse de almohadillas o rellenos que combinan con todos los cojines. Son 4 registros con este "StockCode". Y parecen válidos. Con un "UnitPrice" muy bajo. Pero sin embargo no dejan de ser válidos. Vamos a dejarlos.

In [48]:
df[df["StockCode"] == "B"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

Parecen ser ajustes contables. Los vamos a descartar.

In [49]:
df[df["StockCode"] == "CRUK"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
317508,C564763,CRUK,CRUK Commission,-1,2011-08-30 10:49:00,1.60,14096.0,United Kingdom
324023,C565382,CRUK,CRUK Commission,-1,2011-09-02 15:45:00,13.01,14096.0,United Kingdom
333779,C566216,CRUK,CRUK Commission,-1,2011-09-09 15:17:00,15.96,14096.0,United Kingdom
338848,C566565,CRUK,CRUK Commission,-1,2011-09-13 12:32:00,52.24,14096.0,United Kingdom
351003,C567655,CRUK,CRUK Commission,-1,2011-09-21 14:40:00,608.66,14096.0,United Kingdom
361603,C568345,CRUK,CRUK Commission,-1,2011-09-26 15:28:00,447.56,14096.0,United Kingdom
372785,C569245,CRUK,CRUK Commission,-1,2011-10-03 09:57:00,361.59,14096.0,United Kingdom
390002,C570487,CRUK,CRUK Commission,-1,2011-10-10 17:12:00,411.92,14096.0,United Kingdom
401767,C571440,CRUK,CRUK Commission,-1,2011-10-17 13:31:00,495.98,14096.0,United Kingdom
416464,C572551,CRUK,CRUK Commission,-1,2011-10-24 17:07:00,425.14,14096.0,United Kingdom
429996,C573575,CRUK,CRUK Commission,-1,2011-10-31 14:09:00,606.00,14096.0,United Kingdom
455284,C575606,CRUK,CRUK Commission,-1,2011-11-10 12:37:00,517.51,14096.0,United Kingdom
467437,C576338,CRUK,CRUK Commission,-1,2011-11-14 15:27:00,1038.75,14096.0,United Kingdom
494745,C578269,CRUK,CRUK Commission,-1,2011-11-23 13:39:00,849.93,14096.0,United Kingdom
508561,C579195,CRUK,CRUK Commission,-1,2011-11-28 15:54:00,987.14,14096.0,United Kingdom
528087,C580726,CRUK,CRUK Commission,-1,2011-12-05 17:17:00,1100.44,14096.0,United Kingdom

Según internet. CRUK puede referirse a una organización benéfica de UK dedicada a la investigación del cáncer. Una 'commission' podría hacer referencia a donaciones o comisiones destinadas a esta organización.

No representa un consumo que nos sea pertinente para el análisis de clientes, por lo que lo vamos a excluir.

Con esto damos por terminado el análisis de StockCode.

## Resumen

- POST: representa costos de envío. Lo vamos a excluir.
- D: representa descuentos. Lo vamos a excluir.
- C2: represneta costos de envío. Lo vamos a excluir.
- DOT: representa costos de envío. Lo vamos a excluir.
- M: representa cargas manuales. Lo vamos a excluir.
- BANK CHARGES: representa costos bancarios. Lo vamos a excluir.
- S: representa muestras gratis. Lo vamos a excluir.
- AMAZONFEE: representa tarifas de Amazon por ventas en plataforma. Lo vamos a excluir.
- ^DCGS: no sabemos qué representan. Lo vamos a excluir.
- ^gift: representa regalos. Lo vamos a excluir.
- m: representa cargas manuales. Lo vamos a excluir.
- PADS: representa compras de almohadillas. Lo vamos a CONSERVAR.
- B: representa ajustes contables. Lo vamos a excluir.
- CRUK: representa comisinones a una organización benéfica. Lo vamos a excluir.